# Generated by Django 5.0.2 on 2024-02-09 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_category_good_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='color',
            field=models.CharField(choices=[('red', 'Красное'), ('white', 'Белое')], default='red', max_length=255, verbose_name='Цвет'),
        ),
    ]
