# Generated by Django 5.0.2 on 2024-02-09 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0005_good_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Отзыв')),
                ('rate', models.IntegerField(default=0, verbose_name='Оценка')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
    ]
