# Generated by Django 5.0.2 on 2024-02-09 15:53

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0007_alter_review_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='title',
            field=tinymce.models.HTMLField(),
        ),
    ]
