# Generated by Django 5.0.2 on 2024-02-10 04:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0011_alter_good_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания'),
        ),
    ]
