# Generated by Django 5.0.2 on 2024-02-09 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_payment_order_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='title',
            field=models.CharField(choices=[('cash', 'наличные'), ('card', 'карта')], max_length=255, verbose_name='Оплата'),
        ),
    ]
